### ISSUE TITLE
Problem with arithmetic evaluations

### ISSUE THREAD

**Issue by kaikoveritch** [unige-semantics-2017/expressions#1]
We've only seen one method to evaluate arithmetic operations by accessing their integer value yet and it had a breaking bug. How are we supposed to do the evaluation without using that approach or the representation of Naturals through the successor function ? Is there another way to access value ?

**Comment by saucisson** [comment]
Here the representation of integer numbers (not naturals only) is done with a list of digits. You have seen in the course how to handle addition. You can solve the homework without the breaking things.

**Comment by kaikoveritch** [comment]
So... Does that mean we have to manually specify the sum of every pair of digits ?

**Comment by saucisson** [comment]
Yes !

Hint: if you are lazy, you can try to generate this code...
