### ISSUE TITLE
Type valeur de retour des fonctions arithmétiques

### ISSUE THREAD

**Issue by arthurdeschamps** [unige-semantics-2017/expressions#2]
Je ne comprends pas pourquoi les 4 fonctions arithmétiques retournent toutes des Map.
Est-ce que, par exemple, la fonction `add(Value(1), Value(3))` doit retourner quelque-chose comme:

`["left" : Value(1), "operation" : "+", "right" : Value(3)]`

A première vue je pensais qu'il fallait retourner à chaque fois le résultat, par exemple `Value(4)` dans le cas ci-dessus, mais cela ne me semble pas compatible avec la signature de la fonction.

**Comment by saucisson** [comment]
Comme expliqué en exercices, on construit d'abord la syntaxe abstraite, puis **ensuite** on en donne la sémantique. Il faut donc, en effet, retourner un terme (ici une `Map`) qui représente l'opérations.

**Comment by arthurdeschamps** [comment]
Ok je vois, merci.
