### ISSUE TITLE
Weird results in a solve

### ISSUE THREAD

**Issue by kaikoveritch** [unige-semantics-2017/expressions#3]
I'm testing a recursive Goal function that uses another function I defined to increment a "counter" parameter for the next call. It wasn't working so I checked the value of the counter on each call only to get this:
`cons(0, LogicKit.List.empty)`
`_₀`
`_₁`
The first output is simply 0 (nothing alarming here), but then, I get those weird characters instead of 1,2,... The weirdest part is that my increment function seems to be otherwise perfectly working (I've tested it quite a lot).

Any clues why that is happening ? Or what those characters are ?

**Comment by saucisson** [comment]
@kyouko-taiga any idea?

**Comment by kyouko-taiga** [comment]
Anything that looks like `_₀`, `_₁`, ... is an instance of `Unassigned`.

When you reify a substitution map (i.e. call `Substitution.reified()`), LogicKit will search for any variable that doesn't have an assignment in your system, and will replace it with an instance of `Unassigned` (see [here](https://github.com/kyouko-taiga/LogicKit/blob/88be3f65ea9ca6a0a35b952eac14e3f41c1d02ab/Sources/LogicKit.swift#L393)).

Here's a minimal example that would generate unassigned values:
```swift
let x = Variable(named: "x")
let system = fresh { y in x ≡ y }
for solution in solve(system) {
    print(solution.reified()[x])
}
// Prints "_₀"
```

The problem probably comes from your program.
