### ISSUE TITLE
NOT boolean evaluation not working

### ISSUE THREAD

**Issue by GiovannaTheo** [unige-semantics-2017/expressions#4]
As explained during the exercise session, my evaluation function for the logic op NOT does not work. Here's the function: 
```
func evalBoolean (input: Term, output: Term) -> Goal {
    return
        //Basic cases
        (input === t && output === t) || (input === f && output === f) ||
       //NOT
       freshn { g in
            let r  = g ["r"]
            let rv = g ["rv"]
            return input === not(r) &&
                evalBoolean(input: r, output: rv) &&
                ((rv === f && output === t) || (rv === t && output === f))
        }
}
```

`t` and `f` respectively stand for `True` and `False`.

And here's the tests: 

```  
func testNot() {
        let t = not (Value (true))
        let v = Variable (named: "v")
        let goal = evalBoolean(input: t, output: v)
        print("")
        for r in solve (goal) {
            print (r.reified () [v])
        }
        print("WORKING")
    }
```

When running the code, it just loops on this test and does not display the expected result. Other functions (AND, OR, ...) do work without any problem. 

Any idea ?

Thanks.

**Comment by saucisson** [comment]
Please commit your code to allow me to see it.

**Comment by GiovannaTheo** [comment]
<img width="988" alt="capture d ecran 2017-04-25 a 10 26 44" src="https://cloud.githubusercontent.com/assets/25910997/25375667/bd355e3c-29a1-11e7-8654-30d48ae6e673.png">

Can't you see it in my repo ? I added you as contributor as well.

**Comment by saucisson** [comment]
It was really difficult to find, but here is the bug:

```swift
func not (_ of: Term) -> Map {
    return [
        "op": Value ("not"),
        "what": of, // of instead of t
    ]
}
```

**Comment by GiovannaTheo** [comment]
<img width="732" alt="capture d ecran 2017-04-25 a 11 05 26" src="https://cloud.githubusercontent.com/assets/25910997/25377189/224e187c-29a7-11e7-9473-f2f5a8ba7748.png">

Perfect! Thank you!

**Comment by saucisson** [comment]
Please use assertions in your tests instead of prints.
