### ISSUE TITLE
Evaluation finale

### ISSUE THREAD

**Issue by arthurdeschamps** [unige-semantics-2017/expressions#5]
Concernant l'évaluation finale, c'est-à-dire la fonction `eval`, je ne suis pas sûr de comment l'utiliser. 
En particulier, quels devrait être le style d'input et d'output ?
J'avais pensé à quelque chose comme:
```
input === List.cons(add(5,8, x), List.cons(greaterThan(x,10,y), List.cons(and(y, true))) 
eval(input: input, output: var)
```
pour vérifier par exemple que (5 + 8 > 10 && true) == true ou false.
Est-ce que c'est bon, ou rien avoir ?

**Comment by saucisson** [comment]
Le `eval` final prend simplement n'importe quelle expression (arithmétique ou booléenne) et retourne son résultat.

**Comment by arthurdeschamps** [comment]
Donc, la fonction pourrait très bien accepter:
```eval(input: and(greaterthan(4,5),equal(4,6)), output: x)```
et quand on ferait le `solve` on trouverait `x = f` par exemple ?

**Comment by saucisson** [comment]
Tout à fait.

**Comment by arthurdeschamps** [comment]
Merci !
